"""
Shared Telegram integration utilities for Adhikar-Aina.

This module is designed to be reused by:
- Telegram bot runtime (async handlers)
- Databricks automation triggers (sync jobs)
"""

from __future__ import annotations

import asyncio
import io
import json
import os
from datetime import datetime
from typing import Any, Dict, Optional

from fpdf import FPDF
from pyspark.sql import SparkSession
from pyspark.sql import functions as F
from telegram import Bot

MAPPING_TABLE = "workspace.default.telegram_user_mapping"
CERT_TABLE = "workspace.default.aa_adhikar_certificates"
DEFAULT_ACTION = "Visit nearest facilitation center with required documents."


def get_spark() -> SparkSession:
    try:
        return spark  # type: ignore[name-defined]
    except NameError:
        return SparkSession.builder.appName("adhikar-telegram-integration").getOrCreate()


def ensure_mapping_table(spark_session: Optional[SparkSession] = None) -> None:
    ss = spark_session or get_spark()
    if ss.catalog.tableExists(MAPPING_TABLE):
        return

    ss.sql(
        f"""
        CREATE TABLE IF NOT EXISTS {MAPPING_TABLE} (
            citizen_id STRING,
            telegram_chat_id STRING,
            telegram_username STRING,
            updated_at TIMESTAMP
        ) USING DELTA
        """
    )


def save_chat_mapping(
    citizen_id: str,
    chat_id: int,
    username: Optional[str] = None,
    spark_session: Optional[SparkSession] = None,
) -> None:
    ss = spark_session or get_spark()
    ensure_mapping_table(ss)

    payload = [
        (
            str(citizen_id).strip(),
            str(chat_id),
            (username or "").strip() or None,
            datetime.utcnow(),
        )
    ]
    incoming = ss.createDataFrame(
        payload,
        schema="citizen_id string, telegram_chat_id string, telegram_username string, updated_at timestamp",
    )
    incoming.createOrReplaceTempView("_incoming_mapping")

    ss.sql(
        f"""
        MERGE INTO {MAPPING_TABLE} AS target
        USING _incoming_mapping AS source
        ON target.citizen_id = source.citizen_id
        WHEN MATCHED THEN UPDATE SET
            telegram_chat_id = source.telegram_chat_id,
            telegram_username = source.telegram_username,
            updated_at = source.updated_at
        WHEN NOT MATCHED THEN INSERT *
        """
    )


def get_chat_id_for_citizen(citizen_id: str, spark_session: Optional[SparkSession] = None) -> Optional[str]:
    ss = spark_session or get_spark()
    if not ss.catalog.tableExists(MAPPING_TABLE):
        return None

    row = (
        ss.table(MAPPING_TABLE)
        .filter(F.col("citizen_id") == F.lit(str(citizen_id).strip()))
        .select("telegram_chat_id")
        .orderBy(F.col("updated_at").desc())
        .limit(1)
        .collect()
    )
    if not row:
        return None
    return row[0]["telegram_chat_id"]


def get_citizen_id_for_chat(chat_id: int, spark_session: Optional[SparkSession] = None) -> Optional[str]:
    ss = spark_session or get_spark()
    if not ss.catalog.tableExists(MAPPING_TABLE):
        return None

    row = (
        ss.table(MAPPING_TABLE)
        .filter(F.col("telegram_chat_id") == F.lit(str(chat_id)))
        .select("citizen_id")
        .orderBy(F.col("updated_at").desc())
        .limit(1)
        .collect()
    )
    if not row:
        return None
    return row[0]["citizen_id"]


class AdhikarPDF(FPDF):
    def header(self):
        self.set_font("helvetica", "B", 16)
        self.set_text_color(0, 71, 171)
        self.cell(0, 10, "GOVERNMENT OF INDIA", ln=True, align="C")
        self.set_font("helvetica", "I", 10)
        self.cell(0, 10, "Adhikar-Aina Sovereign Proof-of-Right", ln=True, align="C")
        self.ln(8)

    def footer(self):
        self.set_y(-15)
        self.set_font("helvetica", "I", 8)
        self.cell(0, 10, f"Page {self.page_no()} | Generated by Adhikar-Aina", align="C")


def create_certificate_pdf_bytes(cert_data: Dict[str, Any]) -> bytes:
    pdf = AdhikarPDF()
    pdf.add_page()

    pdf.set_font("helvetica", "B", 12)
    pdf.cell(0, 9, f"Certificate ID: {cert_data.get('certificate_id', 'N/A')}", ln=True)
    pdf.set_font("helvetica", "", 11)
    pdf.cell(0, 8, f"Issued Date: {cert_data.get('issued_date', 'N/A')}", ln=True)
    pdf.ln(3)

    pdf.set_font("helvetica", "B", 12)
    pdf.cell(0, 8, "Citizen Summary", ln=True)
    pdf.set_font("helvetica", "", 10)
    pdf.multi_cell(0, 7, cert_data.get("citizen_summary", ""))
    pdf.ln(2)

    pdf.set_font("helvetica", "B", 12)
    pdf.cell(0, 8, "Eligible Entitlements", ln=True)

    for scheme in cert_data.get("top_schemes", []):
        pdf.set_font("helvetica", "B", 10)
        pdf.multi_cell(
            0,
            7,
            f"- {scheme.get('scheme_name', 'N/A')} ({scheme.get('scheme_code', 'N/A')})",
        )
        pdf.set_font("helvetica", "", 10)
        pdf.multi_cell(0, 6, f"  Benefit: {scheme.get('benefit', '')}")
        pdf.multi_cell(0, 6, f"  Legal Basis: {scheme.get('legal_basis', '')}")
        pdf.multi_cell(0, 6, f"  Action: {scheme.get('action_required', DEFAULT_ACTION)}")
        pdf.ln(1)

    disclaimer = cert_data.get("disclaimer")
    if disclaimer:
        pdf.ln(2)
        pdf.set_font("helvetica", "I", 9)
        pdf.multi_cell(0, 6, disclaimer)

    return pdf.output(dest="S").encode("latin1")


def get_certificate_for_citizen(citizen_id: str, spark_session: Optional[SparkSession] = None) -> Dict[str, Any]:
    ss = spark_session or get_spark()

    table_df = ss.table(CERT_TABLE)
    available_cols = set(table_df.columns)
    payload_cols = [c for c in ["adhikar_certificate", "certificate_json"] if c in available_cols]
    if not payload_cols:
        raise ValueError(f"No certificate payload column found in {CERT_TABLE}")

    row = (
        table_df
        .filter(F.col("citizen_id") == F.lit(str(citizen_id).strip()))
        .orderBy(F.col("generated_at").desc_nulls_last(), F.col("timestamp").desc_nulls_last())
        .select(*payload_cols)
        .limit(1)
        .collect()
    )

    if not row:
        raise ValueError(f"No certificate found for citizen_id={citizen_id}")

    cert_text = row[0]["adhikar_certificate"] if "adhikar_certificate" in row[0].asDict() else None
    if cert_text is None:
        cert_text = row[0]["certificate_json"]

    if not cert_text:
        raise ValueError(f"Certificate payload is empty for citizen_id={citizen_id}")

    return json.loads(cert_text)


async def send_telegram_message(
    chat_id: str | int,
    text: str,
    pdf_bytes: Optional[bytes] = None,
    pdf_filename: str = "Adhikar_Certificate.pdf",
    token: Optional[str] = None,
) -> None:
    bot_token = token or os.getenv("TELEGRAM_BOT_TOKEN")
    if not bot_token:
        raise ValueError("TELEGRAM_BOT_TOKEN is missing")

    bot = Bot(token=bot_token)
    await bot.send_message(chat_id=chat_id, text=text)

    if pdf_bytes:
        await bot.send_document(
            chat_id=chat_id,
            document=io.BytesIO(pdf_bytes),
            filename=pdf_filename,
            caption="🙏 Here is your mandate-compliant Proof-of-Right certificate.",
        )


def send_telegram_message_sync(
    chat_id: str | int,
    text: str,
    pdf_bytes: Optional[bytes] = None,
    pdf_filename: str = "Adhikar_Certificate.pdf",
    token: Optional[str] = None,
) -> None:
    coroutine = send_telegram_message(
        chat_id=chat_id,
        text=text,
        pdf_bytes=pdf_bytes,
        pdf_filename=pdf_filename,
        token=token,
    )

    try:
        asyncio.run(coroutine)
    except RuntimeError:
        # Fallback for environments where an event loop already exists.
        loop = asyncio.new_event_loop()
        try:
            loop.run_until_complete(coroutine)
        finally:
            loop.close()


def format_new_benefit_message(scheme_name: str, benefit: str, action: Optional[str] = None) -> str:
    next_step = action or DEFAULT_ACTION
    return (
        "🔔 New Benefit Unlocked!\n"
        f"You are now eligible for {scheme_name}\n"
        f"💰 Benefit: {benefit}\n"
        f"📍 Action: {next_step}"
    )
